"use strict";
const $ = id => document.getElementById(id);
const state = {user:null, project:null, conversation:null, projects:[], conversations:[], archived:false, setup:false, runs:[], activeRun:null, busy:false, epoch:0, messageSignature:"", pending:null,eventSource:null,eventRun:null};
const labels = {queued:"排队中",running:"生成中",completed:"已完成",failed:"失败",waiting_user:"等待补充",cancelled:"已取消",cancelling:"取消中"};
const errors = {login_required:"请先登录",invalid_credentials:"用户名或密码不正确",login_rate_limit:"登录尝试过多，请稍后再试",invalid_input:"请检查填写内容",project_busy:"该项目已有任务正在运行，请稍后发送",conversation_archived:"请先恢复这条对话",idempotency_content_conflict:"同一消息编号对应了不同内容，请刷新后重试",invalid_request_origin:"请求来源校验失败，请重新打开本机页面"};
async function api(url, options={}) {
  const response = await fetch(url, {...options, headers:{"Content-Type":"application/json","X-Copilot-Request":"1",...(options.headers||{})}});
  const body = await response.json().catch(()=>({}));
  if(!response.ok) {const error=new Error(errors[body.detail]||body.detail||"请求失败，请稍后重试");error.status=response.status;throw error;}
  return body;
}
const json = body => JSON.stringify(body);
function node(tag, text, className) {const element=document.createElement(tag);if(text!==undefined)element.textContent=text;if(className)element.className=className;return element;}
let toastTimer;
function toast(text){const dialogs=document.querySelectorAll('dialog[open]');(dialogs[dialogs.length-1]||document.body).append($("toast"));$("toast").textContent=text;$("toast").hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("toast").hidden=true,4500);}
async function named(title, current=""){
  const dialog=$("name-dialog");$("name-title").textContent=title;$("name-input").value=current;dialog.returnValue="";dialog.showModal();$("name-input").focus();
  return new Promise(resolve=>dialog.addEventListener("close",()=>resolve(dialog.returnValue==="ok"?$("name-input").value.trim():null),{once:true}));
}
function selectedConversation(){return state.conversations.find(c=>c.id===state.conversation);}
function stopRunEvents(){if(state.eventSource)state.eventSource.close();state.eventSource=null;state.eventRun=null;}
function watchRun(id){if(!id||state.eventRun===id)return;stopRunEvents();const source=new EventSource(`/api/runs/${id}/events`);state.eventSource=source;state.eventRun=id;for(const type of ["queued","started","retry_scheduled","cancel_requested","cancelled","completed","failed"]){source.addEventListener(type,async()=>{if(id!==state.eventRun)return;await loadMessages();if(["cancelled","completed","failed"].includes(type))stopRunEvents();});}}
function updateControls(){const conversation=selectedConversation();state.busy=state.runs.some(r=>["queued","running","waiting_user","cancelling"].includes(r.status));$("send").disabled=!conversation||conversation.archived||state.busy;$("message-input").disabled=!conversation||conversation.archived;$("rename-conversation").disabled=!conversation;$("archive-conversation").disabled=!conversation;$("new-conversation").disabled=!state.project;$("rename-project").disabled=!state.project;$("archive-conversation").textContent=conversation?.archived?"恢复":"归档";$("status-line").textContent=conversation?.archived?"这条对话已归档，恢复后可以继续。":state.busy?"正在生成回答。你可以切换对话，稍后返回查看。":"";}
async function loadModels(){const models=await api("/api/models");$("model-select").replaceChildren();for(const model of models){const option=node("option",`${model.purpose} · ${model.name}`);option.value=model.id;$("model-select").append(option);}}
async function enter(user){state.user=user;$("auth").hidden=true;$("workspace").hidden=false;$("user-label").textContent=user.username;await loadModels();await loadProjects();}
async function showAuth(){state.epoch++;state.user=null;$("workspace").hidden=true;$("auth").hidden=false;const setup=await api("/api/setup");state.setup=setup.required;$("auth-title").textContent=state.setup?"创建你的本机账户":"欢迎回来";$("auth-copy").textContent=state.setup?"第一次打开工作台，设置用户名与密码。":"登录后继续你的研究对话。";$("password").autocomplete=state.setup?"new-password":"current-password";}
async function loadProjects(){state.projects=await api("/api/projects");$("projects").replaceChildren();if(!state.projects.length){const option=node("option","先新建一个项目");option.value="";$("projects").append(option);}for(const p of state.projects){const option=node("option",p.title);option.value=p.id;$("projects").append(option);}const saved=localStorage.getItem("copilot-project");if(!state.projects.some(p=>p.id===state.project))state.project=state.projects.some(p=>p.id===saved)?saved:state.projects[0]?.id||null;$("projects").value=state.project||"";await loadConversations();}
async function loadConversations(){stopRunEvents();state.epoch++;const epoch=state.epoch;state.runs=[];state.activeRun=null;state.messageSignature="";$("run-list").replaceChildren();$("run-detail").replaceChildren(node("div","每次回答，都有自己的记录。","inspector-empty"));$("messages").replaceChildren();const loaded=state.project?await api(`/api/projects/${state.project}/conversations?archived=${state.archived}`):[];if(epoch!==state.epoch)return;state.conversations=loaded;if(!state.conversations.some(c=>c.id===state.conversation))state.conversation=state.conversations[0]?.id||null;$("project-label").textContent=state.projects.find(p=>p.id===state.project)?.title||"WORKSPACE";renderConversations();await loadMessages();if(typeof refreshSources==="function")await refreshSources();}
function renderConversations(){const query=$("conversation-search").value.trim().toLowerCase();$("conversations").replaceChildren();const conversations=state.conversations.filter(c=>c.title.toLowerCase().includes(query));for(const c of conversations){const button=node("button",undefined,"conversation-item"+(c.id===state.conversation?" active":""));button.append(node("span","◌"),node("span",c.title));button.addEventListener("click",async()=>{state.epoch++;state.conversation=c.id;state.activeRun=null;state.messageSignature="";state.runs=[];state.pending=null;$("run-list").replaceChildren();$("run-detail").replaceChildren(node("div","选择一条回答查看运行记录。","inspector-empty"));$("message-input").value="";renderConversations();await loadMessages();});$("conversations").append(button);}if(!conversations.length)$("conversations").append(node("div",state.archived?"暂无归档对话":"新建一条对话，开始研究。","empty-list"));$("conversation-heading").textContent=state.archived?"已归档对话":"最近对话";$("toggle-archive").textContent=state.archived?"返回最近":"已归档";$("conversation-title").textContent=selectedConversation()?.title||"准备好开始新的研究了吗？";updateControls();}
async function loadMessages(){const epoch=state.epoch, conversation=state.conversation;if(!conversation){$("messages").replaceChildren();$("welcome").hidden=false;updateControls();return;}const [messages,runs]=await Promise.all([api(`/api/conversations/${conversation}/messages`),api(`/api/conversations/${conversation}/runs`)]);if(epoch!==state.epoch||conversation!==state.conversation)return;state.runs=runs;$("welcome").hidden=messages.length>0;const signature=messages.map(m=>m.id).join("|");if(signature!==state.messageSignature){const area=$("message-area"),nearBottom=area.scrollHeight-area.scrollTop-area.clientHeight<150;$("messages").replaceChildren();for(const message of messages){const article=node("article",undefined,"message "+message.role);const head=node("div",undefined,"message-head");head.append(node("span",message.role==="user"?"你":"R","role-dot"),node("span",message.role==="user"?state.user.username:"Research Copilot"));if(message.mode==="mock")head.append(node("span","开发替身","pill"));article.append(head,node("div",message.content,"message-content"));if(message.result_json&&typeof renderReferences==="function")article.append(renderReferences(message.result_json));if(message.role==="assistant"&&message.run_id){article.dataset.runId=message.run_id;const actions=node("div",undefined,"message-actions"),link=node("button","↗ 查看运行记录","trace-link"),up=node("button","有帮助"+(message.feedback_rating===1?" ✓":""),"trace-link"),down=node("button","需改进"+(message.feedback_rating===-1?" ✓":""),"trace-link");link.onclick=()=>showRun(message.run_id).catch(e=>toast(e.message));up.onclick=()=>saveFeedback(message.id,1);down.onclick=()=>saveFeedback(message.id,-1);actions.append(link,up,down);article.append(actions);}$("messages").append(article);}if(nearBottom||!state.messageSignature)area.scrollTop=area.scrollHeight;state.messageSignature=signature;}renderRuns();updateControls();const active=runs.find(r=>["queued","running","waiting_user","cancelling"].includes(r.status));if(active)watchRun(active.id);if(state.activeRun&&runs.some(r=>r.id===state.activeRun))await showRun(state.activeRun);}
async function saveFeedback(messageId,rating){await api(`/api/messages/${messageId}/feedback`,{method:"POST",body:json({rating})});state.messageSignature="";await loadMessages();toast("反馈已记录并绑定到本次回答。");}
async function exportRun(id){const response=await fetch(`/api/runs/${id}/export`);if(!response.ok)throw new Error("导出失败");const blob=await response.blob(),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`run-${id}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
function focusRunMessage(id){const article=Array.from(document.querySelectorAll(".message.assistant[data-run-id]")).find(item=>item.dataset.runId===id);if(!article)return;document.querySelectorAll(".message.run-focus").forEach(item=>item.classList.remove("run-focus"));article.classList.add("run-focus");article.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>article.classList.remove("run-focus"),1800);}
function focusRunButton(id){const button=Array.from(document.querySelectorAll(".run-button[data-run-id]")).find(item=>item.dataset.runId===id);if(button)button.scrollIntoView({behavior:"smooth",block:"nearest"});}
function renderRuns(){$("run-list").replaceChildren();for(const r of state.runs.slice(0,6)){const button=node("button",undefined,"run-button"+(r.id===state.activeRun?" active":""));button.dataset.runId=r.id;button.append(node("span",r.id.slice(0,8)),node("span",labels[r.status]||r.status));button.onclick=()=>showRun(r.id,{focusMessage:true}).catch(e=>toast(e.message));$("run-list").append(button);}}
async function showRun(id,{focusMessage=false}={}){const epoch=state.epoch;state.activeRun=id;const run=await api(`/api/runs/${id}`);if(epoch!==state.epoch||state.activeRun!==id)return;const box=$("run-detail");box.replaceChildren();for(const [label,value] of [["状态",labels[run.status]||run.status],["运行编号",run.id],["Trace ID",run.trace_id],["模型",run.model],["Prompt 版本",run.prompt_version],["实际用量",run.usage?`${run.usage.total_tokens} tokens`:"尚无用量记录"],["调用费用","未配置价格，暂不估算"]]){box.append(node("div",label,"detail-label"),node("div",value,"detail-value"));}if(run.error_code)box.append(node("p","错误："+run.error_code,"error"));const exportButton=node("button","导出脱敏记录","text-button");exportButton.onclick=()=>exportRun(id).catch(e=>toast(e.message));box.append(exportButton);if(["queued","running","waiting_user","cancelling"].includes(run.status)){const cancel=node("button",run.status==="cancelling"?"正在取消…":"取消运行","text-button");cancel.disabled=run.status==="cancelling";cancel.onclick=async()=>{await api(`/api/runs/${id}/cancel`,{method:"POST"});watchRun(id);await loadMessages();};box.append(cancel);}for(const span of run.spans){const card=node("div",undefined,"span-card");card.append(node("b",span.kind.toUpperCase()+" · "+span.status),node("div",span.name),node("div",span.duration_ms===null?"进行中":`${span.duration_ms} ms`));if(span.metadata.message_ids)card.append(node("div",`上下文包含 ${span.metadata.message_ids.length} 条消息`));if(span.metadata.chunk_ids)card.append(node("div",`检索到 ${span.metadata.chunk_ids.length} 个原文片段`));if(span.metadata.citation_count!==undefined)card.append(node("div",`校验 ${span.metadata.citation_count} 条引用`));if(Object.keys(span.metadata||{}).length){const details=node("details"),summary=node("summary","步骤元数据"),pre=node("pre",JSON.stringify(span.metadata,null,2));details.append(summary,pre);card.append(details);}box.append(card);}renderRuns();focusRunButton(id);if(focusMessage)focusRunMessage(id);}
$("auth-form").onsubmit=async event=>{event.preventDefault();$("auth-submit").disabled=true;$("auth-error").textContent="";try{const user=await api(state.setup?"/api/setup":"/api/login",{method:"POST",body:json({username:$("username").value,password:$("password").value})});$("password").value="";await enter(user);}catch(error){$("auth-error").textContent=error.message;}finally{$("auth-submit").disabled=false;}};
$("new-project").onclick=async()=>{const title=await named("新建项目");if(!title)return;try{const p=await api("/api/projects",{method:"POST",body:json({title})});state.project=p.id;state.conversation=null;state.archived=false;await loadProjects();}catch(e){toast(e.message);}};
$("rename-project").onclick=async()=>{const title=await named("重命名项目",state.projects.find(p=>p.id===state.project)?.title);if(!title)return;try{await api(`/api/projects/${state.project}`,{method:"PATCH",body:json({title})});await loadProjects();}catch(e){toast(e.message);}};
$("projects").onchange=async()=>{state.project=$("projects").value;state.conversation=null;state.archived=false;state.pending=null;$("message-input").value="";localStorage.setItem("copilot-project",state.project);try{await loadConversations();}catch(e){toast(e.message);}};
$("new-conversation").onclick=async()=>{const title=await named("新建对话","新的研究对话");if(!title)return;try{const c=await api(`/api/projects/${state.project}/conversations`,{method:"POST",body:json({title})});state.conversation=c.id;state.archived=false;state.pending=null;await loadConversations();}catch(e){toast(e.message);}};
$("rename-conversation").onclick=async()=>{const title=await named("重命名对话",selectedConversation()?.title);if(!title)return;try{await api(`/api/conversations/${state.conversation}`,{method:"PATCH",body:json({title})});await loadConversations();}catch(e){toast(e.message);}};
$("archive-conversation").onclick=async()=>{try{await api(`/api/conversations/${state.conversation}`,{method:"PATCH",body:json({archived:!selectedConversation().archived})});state.conversation=null;await loadConversations();}catch(e){toast(e.message);}};
$("toggle-archive").onclick=async()=>{state.archived=!state.archived;state.conversation=null;try{await loadConversations();}catch(e){toast(e.message);}};
$("conversation-search").oninput=renderConversations;
$("logout").onclick=async()=>{try{stopRunEvents();await api("/api/logout",{method:"POST"});state.pending=null;await showAuth();}catch(e){toast(e.message);}};
$("message-form").onsubmit=async event=>{event.preventDefault();const content=$("message-input").value.trim(),conversation=state.conversation,options=currentRunOptions();if(!content||!conversation||state.busy)return;if(!state.pending||state.pending.content!==content||state.pending.conversation!==conversation||JSON.stringify(state.pending.options)!==JSON.stringify(options))state.pending={conversation,content,options,client_message_id:crypto.randomUUID()};const pending=state.pending;$("send").disabled=true;try{const result=await api(`/api/conversations/${conversation}/messages`,{method:"POST",body:json({content,client_message_id:pending.client_message_id,...pending.options})});if(conversation===state.conversation){$("message-input").value="";state.pending=null;state.activeRun=result.run_id;watchRun(result.run_id);await loadMessages();}}catch(e){toast(e.message);if(e.status&&e.status!==500)state.pending=null;}finally{updateControls();}};
$("message-input").addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey&&!event.isComposing){event.preventDefault();if(!$("send").disabled)$("message-form").requestSubmit();}});
let polling=false;setInterval(async()=>{if(polling||!state.user||!state.conversation||document.hidden)return;polling=true;try{await loadMessages();}catch(e){if(e.status===401)await showAuth();}finally{polling=false;}},1800);
(async()=>{try{await enter(await api("/api/me"));}catch(e){await showAuth();}})().catch(e=>toast(e.message));
