"use strict";
let contextView={project:null,data:null};
let editingMemory=null;
async function refreshContext(){const project=contextView.project,data=await api(`/api/projects/${project}/context`);if(project!==contextView.project)return;contextView.data=data;$("context-revision").textContent=`项目 revision ${data.revision}`;$("context-objective").value=data.state.objective;$("context-dimensions").value=data.state.dimensions.join("\n");$("memory-list").replaceChildren();for(const memory of data.memories){const card=node("div",undefined,"span-card");card.append(node("p",memory.content));const edit=node("button","编辑"),revoke=node("button","撤销偏好");edit.onclick=()=>{editingMemory=memory;$("memory-content").value=memory.content;$("memory-content").focus();$("memory-form").querySelector("button").textContent="保存偏好修改";};revoke.onclick=()=>mutateMemory(memory,{revoke:true});card.append(edit,revoke);$("memory-list").append(card);}if(!data.memories.length)$("memory-list").append(node("p","暂无保存的偏好。","muted"));$("context-history").replaceChildren();for(const item of data.history)$("context-history").append(node("p",`revision ${item.revision} · ${item.change.kind}${item.change.fields?" · "+item.change.fields.join(", "):""}`));}
async function mutateMemory(memory,change){try{await api(`/api/projects/${contextView.project}/memories/${memory.id}`,{method:"PATCH",body:json({expected_revision:contextView.data.revision,expected_version:memory.version,...change})});await refreshContext();}catch(e){toast(e.message);}}
$("open-context").onclick=async()=>{if(!state.project)return;contextView.project=state.project;editingMemory=null;$("memory-content").value="";$("memory-form").querySelector("button").textContent="记住这条偏好";try{await refreshContext();$("context-dialog").showModal();}catch(e){toast(e.message);}};
$("close-context").onclick=()=>$("context-dialog").close();
$("context-form").onsubmit=async event=>{event.preventDefault();const dimensions=$("context-dimensions").value.split("\n").map(s=>s.trim()).filter(Boolean);if(dimensions.length>12)return toast("最多填写 12 个研究维度");try{await api(`/api/projects/${contextView.project}/state`,{method:"PATCH",body:json({expected_revision:contextView.data.revision,objective:$("context-objective").value,dimensions})});await refreshContext();toast("项目要求已保存；新任务将使用新版本。");}catch(e){toast(e.message);}};
$("memory-form").onsubmit=async event=>{event.preventDefault();if(editingMemory){await mutateMemory(editingMemory,{content:$("memory-content").value});editingMemory=null;$("memory-content").value="";$("memory-form").querySelector("button").textContent="记住这条偏好";return;}try{await api(`/api/projects/${contextView.project}/memories`,{method:"POST",body:json({expected_revision:contextView.data.revision,content:$("memory-content").value})});$("memory-content").value="";await refreshContext();}catch(e){toast(e.message);}};
errors.project_revision_conflict="项目已在其他窗口修改，请关闭后重新打开；本次修改没有覆盖新版本。";
errors.memory_version_conflict="这条偏好已被修改或撤销，请重新打开项目记忆。";
