"use strict";
const sourceState={project:null,selected:new Set(),all:true,files:[]};
function currentRunOptions(){const skill=$("skill-select").value||null,isSearch=skill==="paper-search";return {skill_id:skill,file_ids:isSearch?null:(sourceState.all?null:Array.from(sourceState.selected).sort()),model_id:$("model-select").value||"default",allow_network:isSearch};}
async function refreshSources(){const project=state.project;if(!project)return;if(sourceState.project!==project){sourceState.project=project;sourceState.selected.clear();sourceState.all=true;}const data=await api(`/api/projects/${project}/files`);if(project!==state.project)return;sourceState.files=data.files.filter(f=>!f.deleted_at&&f.kind!=="generated");sourceState.selected=new Set(Array.from(sourceState.selected).filter(id=>sourceState.files.some(f=>f.id===id)));renderSourceOptions();}
function renderSourceOptions(){const box=$("source-options");box.replaceChildren();$("source-all").checked=sourceState.all;for(const file of sourceState.files){const label=node("label"),checkbox=node("input");checkbox.type="checkbox";checkbox.value=file.id;checkbox.checked=sourceState.all||sourceState.selected.has(file.id);checkbox.onchange=()=>{if(sourceState.all){sourceState.all=false;sourceState.selected=new Set(sourceState.files.map(f=>f.id));}if(checkbox.checked)sourceState.selected.add(file.id);else sourceState.selected.delete(file.id);renderSourceOptions();};label.append(checkbox,node("span",`${file.display_name} · ${fileKinds[file.kind]} · ${fileStatuses[file.status]}`));box.append(label);}if(!sourceState.files.length)box.append(node("p","请先从项目文件中上传资料。","muted small"));$("source-summary").textContent=sourceState.all?`全部可用资料（${sourceState.files.filter(f=>f.status==='ready').length} 份就绪）`:`已限定 ${sourceState.selected.size} 份资料`;}
$("source-all").onchange=()=>{sourceState.all=$("source-all").checked;if(!sourceState.all)sourceState.selected.clear();renderSourceOptions();};
function renderReferences(result){const box=node("div",undefined,"citation-list");for(const reference of result.references||[]){const button=fileButton("",()=>openCitation(reference),"citation-card");button.append(node("strong",`[${reference.ordinal}] ${reference.display_name} · ${reference.kind==='user_note'?'个人笔记':`第 ${reference.page} 页`}`),node("span",reference.quote));box.append(button);}for(const source of result.web_sources||[]){const link=node("a",undefined,"citation-card web-source");link.href=source.url;link.target="_blank";link.rel="noopener noreferrer";link.append(node("strong",`[${source.ordinal}] ${source.title}`),node("span",[source.authors,source.year,source.snippet].filter(Boolean).join(" · ")));box.append(link);}for(const artifact of result.artifacts||[]){box.append(fileButton("打开成果 · "+artifact.name,async()=>{library.project=state.project;library.folder=null;library.selected=artifact.file_id;library.version=artifact.version_id;library.page=1;library.trash=false;library.epoch++;$("files-dialog").showModal();await refreshLibrary();},"citation-card"));}return box;}

function updateSkillScope(){const searching=$("skill-select").value==="paper-search";$("source-scope").hidden=searching;$("network-scope").hidden=!searching;$("message-input").placeholder=searching?"输入论文主题、方法名或研究问题……":"描述你的研究问题，或继续之前的讨论……";}
$("skill-select").addEventListener("change",updateSkillScope);updateSkillScope();
async function openCitation(reference){const original=await api(`/api/chunks/${reference.chunk_id}`);library.project=state.project;library.folder=null;library.selected=original.file_id;library.version=original.version_id;library.page=original.page;library.trash=false;library.epoch++;if(!$("files-dialog").open)$("files-dialog").showModal();await refreshLibrary();const notice=node("div",undefined,"citation-focus");notice.append(node("strong",original.current?"本次引用的原文":"历史引用：来源已替换或回收，请重新核查"),node("p",reference.quote));$("file-preview").prepend(notice);$("file-preview").scrollTop=0;}
let sourcePolling=false;setInterval(async()=>{if(sourcePolling||!state.user||!state.project||document.hidden||!sourceState.files.some(f=>['uploaded','parsing','pending_index'].includes(f.status)))return;sourcePolling=true;try{await refreshSources();}catch(e){}finally{sourcePolling=false;}},3500);
$("files-dialog").addEventListener('close',()=>refreshSources().catch(e=>toast(e.message)));
